version: "3"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8050:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      - kafka

  workflow-service:
    build:
      context: ./workflow-service
    volumes:
      - ./workflow-service:/usr/src/app
    ports:
      - "9000:9000"
    depends_on:
      - kafka
    environment:
      - MONGODB_URI=mongodb://workflow-db:27017/workflowdb
      - KAFKA_BROKER_URL=kafka:29092

  # Application / Applicant microservices
  applicant-svc-db:
    image: mongo:latest
    ports:
      - "27001:27017"
    volumes:
      - ./appldb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${APPL_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${APPL_DB_PASSWORD}

  applicant-service:
    build:
      context: ./applicant-service
    volumes:
      - ./applicant-service:/usr/src/app
    ports:
      - "9001:9001" # note to self, move all services to 9000 range
    depends_on:
      - kafka
      - workflow-service
    environment:
      - MONGODB_URI=mongodb://applicant-svc-db:27017/applicantdb
      - KAFKA_BROKER_URL=kafka:29092
      - WORKFLOW_SERVICE_URL=http://workflow-service:9000

  web-app-applicant:
    build:
      context: ./web-app-applicant
      dockerfile: Dockerfile
    volumes:
      - ./web-app-applicant:/usr/src/app
    ports:
      - "3004:3000"
    depends_on:
      - workflow-service

  # Visa worklow microservices
  workflow-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./wfdb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${WORKFLOW_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${WORKFLOW_DB_PASSWORD}

  user-db:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - ./userdb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USER_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${USER_DB_PASSWORD}

  nginx-proxy:
    build:
      context: ./nginx-proxy
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - web-app-applicant
      - workflow-service
